IF
  TimeOfDay(DAY)
  AreaType(DAYNIGHT)
  AreaType(OUTDOOR)
  !AreaType(DUNGEON)
  Global("LaViconiaState","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("LaViconiaState","LOCALS",1)
    ApplySpellRES("LaVSun",Myself)
END

IF
  Global("LaViconiaState","LOCALS",1)
  OR(3)
    !AreaType(OUTDOOR)
    AreaType(DUNGEON)
    TimeOfDay(NIGHT)
THEN
  RESPONSE #100
    SetGlobal("LaViconiaState","LOCALS",0)
    ApplySpellRES("LaVNig",Myself)
END
